### ISSUE TITLE
Prepare Solidus Content for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [nebulab/solidus_content#48]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by AlistairNorman** [comment]
I'll take this one!

**Comment by AlistairNorman** [comment]
This one passed without deprecations up to master without any changes so looks like it's good to go!

**Comment by seand7565** [comment]
Closing as it looks like there's nothing to do here! 🎉
